fixes #30
opencast-ilias/OpencastPageComponent pull request #31
Opened 2024-09-03 13:54 UTC by okaufman

I added a check with array_key_exists() to fix #30

2024-09-13 06:19 UTC, chfsx requested changes

2024-09-13 06:19 UTC, chfsx commented on classes/class.ilOpencastPageComponentPluginGUI.php
> +        if (array_key_exists(self::PROP_RESPONSIVE, $properties)) {
I suggest to use a Null Coalescing Operator:

```
if ((bool)($properties[self::PROP_RESPONSIVE] ?? false) === true) {
    $tpl->setVariable('WIDTH', 'width:100%;');
}
```

as well as a more strict type handling, and last but not least turning the logic from != false to === true which is more readable.

2024-09-13 06:19 UTC, chfsx commented on classes/class.ilOpencastPageComponentPluginGUI.php
> +            switch ($properties[self::PROP_POSITION]) {
Same here, instead of using array_key_exists you can just use 

```
switch ($properties[self::PROP_POSITION] ?? null) {
```

2024-09-25 13:32 UTC, rfcmaXi commented
Can we fix the error and transfer it to the production version?

2024-12-02 14:25 UTC, okaufman commented
Thank you, I changed the PR and added your suggestions

2024-12-02 14:42 UTC, chfsx approved these changes
Thanks, I will merge this to the next release!

2025-01-22 15:55 UTC, dagraf commented
@chfsx When do you have planned to merge this PR? The sooner the better, I would say.

2025-02-20 15:19 UTC, chfsx commented
I rebased and merged locally, this is now part of v8.1.1. Thanks @okaufman !

2025-02-20 15:19 UTC, closed without merging